framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        # reset services after consuming messages
        # reset_on_message: true

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # transport async between service register and service app 
            async_register_application:
                # host to send messages
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        register_application_queue:
                            binding_keys: [ register_application_queue ]
        routing:
            'App\Messenger\Message\UserRegisteredMessage': async_register_application
