framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        failure_transport: failed
        transports:
            async_register_application:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        register_application_queue:
                            binding_keys: [ register_application_queue ]
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        routing:
            'App\Messenger\Message\UserRegisteredMessage': async_register_application
